#pragma once

#include <cstdint>

// Faz 1 Bytecode VM icin komut seti.
// Isimler Turkce tutuldu ki debug ederken okunabilir kalsin.
enum class OpCode : std::uint8_t {
  OP_SABIT = 0,
  OP_BOS,
  OP_DOGRU,
  OP_YANLIS,
  OP_POP,
  OP_KOPYA,
  OP_GET_LOCAL,
  OP_SET_LOCAL,
  OP_GET_GLOBAL,
  OP_SET_GLOBAL,
  OP_ALAN_AL,
  OP_ALAN_YAZ,
  OP_METOD_YAZ,
  OP_INDEKS_AL,
  OP_INDEKS_YAZ,
  OP_UZUNLUK,
  OP_LISTE_OLUSTUR,
  OP_LISTE_PUSH,
  OP_LISTE_REZERVE,
  OP_SOZLUK_OLUSTUR,
  OP_ISLEV_OLUSTUR,
  OP_CAGIR,
  OP_SINIF,
  OP_MIRAS_AL,
  OP_TOPLA,
  OP_CIKAR,
  OP_CARP,
  OP_BOL,
  OP_NEGATE,
  OP_NOT,
  OP_ESIT,
  OP_BUYUK,
  OP_KUCUK,
  OP_VE,
  OP_VEYA,
  OP_YAZDIR,
  OP_ATLA,
  OP_ATLA_EGER_YANLIS,
  OP_DONGU,
  OP_TRY_BASLA,
  OP_TRY_BITIR,
  OP_DON
};
